apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-dep
  labels:
    app: win
spec:
  replicas: 10
  template:
    metadata:
      name: windows-pod
      labels:
        app: win
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: aspnetapp-container
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
  selector:
    matchLabels:
      app: win
