apiVersion: v1
kind: Pod
metadata:
  name: toolbox1
  labels:
    app: toolbox
spec:
  nodeSelector:
    dncnode: aks-podpool-12568644-vmss000000
  containers:
    - name: toolbox
      image: matmerr/toolbox:lite
      env:
        - name: TCP_PORT
          value: "8085"
        - name: UDP_PORT
          value: "8086"
        - name: HTTP_PORT
          value: "8087"
