apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: toolbox
spec:
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      hostNetwork: true
      containers:
      - name: toolbox
        image: acndev.azurecr.io/toolbox:paulj
        env:
        - name: TCP_PORT
          value: "8085"
        - name: UDP_PORT
          value: "8086"
        - name: HTTP_PORT
          value: "8087"
        
