apiVersion: v1
kind: Pod
metadata:
  name: windows-pod-host-mount
spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
      command: ["powershell"]
      args: ["sleep", "5000"]
      volumeMounts:
        - mountPath: /host
          name: host
  volumes:
    - name: host
      hostPath:
        path: /
  nodeSelector:
    kubernetes.io/os: windows
  tolerations:
    - key: "node.cloudprovider.kubernetes.io/uninitialized"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
