apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: windows-daemonset 
spec:
  selector:
    matchLabels:
      app: windows-pod
  template:
    metadata:
      labels:
        app: windows-pod
    spec:
      containers:
        - name: windows-container2
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          command: ["powershell", "Start-Sleep", "-s", "3600"]
      nodeSelector:
        kubernetes.io/os: windows
