apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: windows-daemonset
spec:
  selector:
    matchLabels:
      app: windows-pod
  template:
    metadata:
      labels:
        app: windows-pod
    spec:
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\Local service"
      hostNetwork: true
      containers:
      - name: win-container
        image: acnpublic.azurecr.io/azure-cns-win:v1.4.12-43-g21f203db8-dirty
        imagePullPolicy: Always # Change to IfNotPresent after development
        args: [ "-log-target", "stdoutfile", "-log-location", "C:\\k"]
        volumeMounts:
        - name: log-state-lock
          mountPath: /k
        - name: cns-config
          mountPath: /etc/azure-cns
        - name: cni-bin
          mountPath: /k/azure-cni/bin
        ports:
        - containerPort: 10090
      volumes:
      - name: log-state-lock
        hostPath:
          path: /k
          type: Directory
      - name: cns-config
        configMap:
          name: cns-config
      - name: cni-bin
        hostPath:
          path: /k/azurecni/bin
          type: Directory
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cns-config
data:
  cns_config.json: |
    {
      "TelemetrySettings": {
          "TelemetryBatchSizeBytes": 16384,
          "TelemetryBatchIntervalInSecs": 15,
          "RefreshIntervalInSecs": 15,
          "DisableAll": false,
          "HeartBeatIntervalInMins": 30,
          "DebugMode": false,
          "SnapshotIntervalInMins": 60
      },
      "ManagedSettings": {
          "PrivateEndpoint": "",
          "InfrastructureNetworkID": "",
          "NodeID": "",
          "NodeSyncIntervalInSeconds": 30
      },
      "ChannelMode": "CRD",
      "InitializeFromCNI": true
    }
