apiVersion: v1
kind: Pod
metadata:
  name: windows-pod-2
spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
      command: ["powershell", "Start-Sleep", "-s", "3600"]
  nodeSelector:
    kubernetes.io/os: windows
